import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import HeadComp from '@/components/HeadComp'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SnapNotes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <HeadComp />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
